 name: Deploy to Server 
   on: 
     push: 
       branches: [ main ] 
 
   jobs: 
     deploy: 
       runs-on: ubuntu-latest 
       steps: 
         - name: Deploy over SSH 
           uses: appleboy/ssh-action@v0.1.10 
           with: 
             host: ${{ secrets.SSH_HOST }} 
             username: ${{ secrets.SSH_USER }} 
             key: ${{ secrets.SSH_PRIVATE_KEY }} 
             script: | 
               docker pull yourname/app:latest 
               docker stop app || true 
               docker rm app || true 
               docker run -d --name app -p 80:80 yourname/app:latest