name: Deploy to Server 
on: 
  push: 
    branches: [ main ] 
 
jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Deploy over SSH 
        uses: appleboy/ssh-action@v0.1.10 
        with: 
          host: ${{ secrets.SSH_HOST }} 
          username: ${{ secrets.SSH_USER }} 
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          script: | 
            sudo docker pull lemahkuat96/frontend:latest 
            sudo docker stop app || true 
            sudo docker rm app || true 
            sudo docker run -d --name app -p 3000:80 lemahkuat96/frontend:latest     